version: '3'

services:
    furynode:
        image: "nemo/fury:${FURY_TAG:-v0.15.1}"
        ports:
            # open default nemo rpc port
            - "26657:26657"
        volumes:
            - "./nemo/initstate/.fud/config:/root/.fud/config"
            - "./nemo/initstate/.kvcli/:/root/.kvcli/"
        # start the blockchain, and set rpc to listen to connections from outside the container
        command: ["sh", "-c", "/root/.fud/config/init-data-directory.sh && fud start --pruning=nothing --rpc.laddr=tcp://0.0.0.0:26657"]
    furyrest:
        image: "nemo/fury:${FURY_TAG:-v0.15.1}"
        ports:
            # open default rest port
            - "1317:1317"
        command: ["kvcli", "rest-server", "--node=tcp://furynode:26657", "--trust-node", "--laddr=tcp://0.0.0.0:1317", "--unsafe-cors"]
